# Generated by Django 4.2.3 on 2023-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='icone_lupa',
            field=models.ImageField(blank=True, default='', upload_to='busca/%Y/%m/'),
        ),
    ]
