# Generated by Django 4.2.3 on 2023-07-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup_icone_lupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='icone_lupa',
        ),
    ]
